-- 认证模块
USE prom_lens;

CREATE TABLE IF NOT EXISTS prom_lens_authn_user (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL UNIQUE COMMENT '用户名称',
  password VARCHAR(128) COMMENT '用户密码',
  nickname VARCHAR(32) COMMENT '中文名称',
  email VARCHAR(64) NOT NULL UNIQUE COMMENT '邮箱地址',
  phone VARCHAR(11) DEFAULT NULL UNIQUE COMMENT '手机号码',
  is_active TINYINT(1) DEFAULT 1 COMMENT '活跃状态',
  is_superuser TINYINT(1) DEFAULT 0 COMMENT '超级管理员',
  is_ldap TINYINT(1) DEFAULT 0 COMMENT 'LDAP 认证',
  dn VARCHAR(255) DEFAULT NULL UNIQUE COMMENT 'LDAP DN',
  creator VARCHAR(64) NOT NULL COMMENT '创建人',
  last_login DATETIME(3) DEFAULT NULL COMMENT '最后登录时间',
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
