[request_definition]
r = sub, cluster, namespace, resource, act

[policy_definition]
p = sub, cluster, namespace, resource, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && \
    (p.cluster == "*" || r.cluster == p.cluster) && \
    (p.namespace == "*" || r.namespace == p.namespace) && \
    (p.resource == "*" || r.resource == p.resource) && \
    (p.act == "*" || r.act == p.act)